<?php
/*
* Implements hook_ctools_plugin_directory().
*/
function ardistro_bloques_ctools_plugin_directory($owner, $plugin_type) {
   if ($owner == 'ctools' && $plugin_type == 'content_types') {
     return 'plugins/' . $plugin_type;
   }
 }

/*
* Implements hook_theme().
*/
function ardistro_bloques_theme($existing, $type, $theme, $path) {
  return array(
    'ardistro_bloques_alerta' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_alerta'
    ),
    'ardistro_bloques_carrousel' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_carrousel'
    ),
    'ardistro_bloques_campo_categoria_noticia' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_campo_categoria_noticia'
    ),
    'ardistro_bloques_campo_costo' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_campo_costo'
    ),
    'ardistro_bloques_campo_links_relacionados' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_campo_links_relacionados'
    ),
    'ardistro_bloques_campo_paginas_relacionadas' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_campo_paginas_relacionadas'
    ),
    'ardistro_bloques_campo_requisitos' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_campo_requisitos'
    ),
    'ardistro_bloques_campo_siglas_area' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_campo_siglas_area'
    ),
    'ardistro_bloques_campo_tags' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_campo_tags'
    ),
    'ardistro_bloques_campo_tipo_tramite' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_campo_tipo_tramite'
    ),
    'ardistro_bloques_galeria_imagenes_min' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_galeria_imagenes_min'
    ),
    'ardistro_bloques_galeria_imagenes_min_item' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_galeria_imagenes_min_item'
    ),
    'ardistro_bloques_listado_vertical' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_vertical'
    ),
    'ardistro_bloques_listado_vertical_item' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_vertical_item'
    ),
    'ardistro_bloques_listado_horizontal' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_horizontal'
    ),
    'ardistro_bloques_listado_horizontal_item' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_horizontal_item'
    ),
    'ardistro_bloques_listado_destacado_vertical' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_destacado_vertical'
    ),
    'ardistro_bloques_listado_destacado_vertical_item' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_destacado_vertical_item'
    ),
    'ardistro_bloques_listado_destacado_horizontal' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_destacado_horizontal'
    ),
    'ardistro_bloques_listado_destacado_horizontal_item' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_destacado_horizontal_item'
    ),
    'ardistro_bloques_listado_con_imagen_vertical' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_con_imagen_vertical'
    ),
    'ardistro_bloques_listado_con_imagen_vertical_item' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_con_imagen_vertical_item'
    ),
    'ardistro_bloques_listado_con_imagen_horizontal' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_con_imagen_horizontal'
    ),
    'ardistro_bloques_listado_con_imagen_horizontal_item' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_con_imagen_horizontal_item'
    ),
    'ardistro_bloques_listado_vacio' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_listado_vacio'
    ),
    'ardistro_bloques_imagen_destacada' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_imagen_destacada'
    ),
    'ardistro_bloques_titulo' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_titulo'
    ),
    'ardistro_bloques_texto' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_texto'
    ),
    'ardistro_bloques_shortcut' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_shortcut'
    ),
      'ardistro_bloques_shortcut_interno' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_shortcut_interno'
    ),
    'ardistro_bloques_separador' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_separador'
    ),
    'ardistro_bloques_separador_linea' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_separador_linea'
    ),
    'ardistro_bloques_redes_sociales_compartir' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_redes_sociales_compartir'
    ),
    'ardistro_bloques_redes_sociales_timeline_facebook' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_redes_sociales_timeline_facebook'
    ),
    'ardistro_bloques_redes_sociales_timeline_twitter' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_redes_sociales_timeline_twitter'
    ),
    'ardistro_bloques_imagen_con_link' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_imagen_con_link'
    ),
    'ardistro_bloques_imagen_destacada_home' => array(
      'path' => drupal_get_path('module', 'ardistro_bloques') . '/templates',
      'template' => 'ardistro_bloques_imagen_destacada_home'
    ),
  );
}
