<?php

/**
 * Implements hook_block_info().
 */
function ardistro_footer_block_info() {
  $blocks = array();
  $blocks['my_block'] = array(
    'info' => t('Bloque Customizable Para Footer'),
  );
  
  return $blocks;
}


/**
 *  hook_block_configuracion - Admin del block().
 */
function ardistro_footer_block_configure($delta='') {
    $form= array();
    if ($delta=='my_block') {
        $form['my_image_block_image'] = array(
            '#type'=>'managed_file',
            '#title'=>t('Imagen Izquierda'),
            '#size'=>40,
            '#description'=>t('Cualquier archivo tipo .jpg, .png, .svg, .gif'),
            '#upload_location'=>'public://',
            '#default_value'=>variable_get('my_image_block_image'),
        );

        $form["alt_img_izquierda"] = array(
            "#type" => 'textfield',
            "#title" => t("Alt Imagen Izquierda"),
            "#default_value" => variable_get("alt_img_izquierda")
        );


        $form['texto'] = array(
            '#type'=>'textarea',
            '#title'=>t('Texto centrico.'),
            '#default_value'=>variable_get('texto'),
        );

        
        $form['my_image_block_image2'] = array(
            '#type'=>'managed_file',
            '#title'=>t('Imagen Derecha'),
            '#size'=>40,
            '#description'=>t('Cualquier archivo tipo .jpg, .png, .svg, .gif'),
            '#upload_location'=>'public://',
            '#default_value'=>variable_get('my_image_block_image2'),
        );        

        $form["alt_img_derecha"] = array(
            "#type" => 'textfield',
            "#title" => t("Alt Imagen derecha"),
            "#default_value" => variable_get("alt_img_derecha")
        );
    }

    return$form;
}


/**
 * hook_block_save - Salva el form en la DB.
 */
function ardistro_footer_block_save($delta = '', $edit = array()) {
    if ($delta=='my_block') {

        //Guardo y subo al la imagen 1
        variable_set('my_image_block_image',$edit['my_image_block_image']);
        $file=file_load(variable_get('my_image_block_image',$edit['my_image_block_image']));

        if (is_object($file)) {
            $file->status=FILE_STATUS_PERMANENT;
            file_save($file);
            
            
            file_usage_add($file,'myblock','block',$file->fid);
        }

        //Guardo y subo la imagen 2
        variable_set('my_image_block_image2',$edit['my_image_block_image2']);
        $file2=file_load(variable_get('my_image_block_image2',$edit['my_image_block_image2']));

        if (is_object($file2)) {
            $file2->status=FILE_STATUS_PERMANENT;
            file_save($file2);
            
            file_usage_add($file2,'myblock','block',$file2->fid);
        }
 
        //Guardo el texto
        variable_set('texto',$edit['texto']);
        variable_set('alt_img_izquierda', $edit['alt_img_izquierda']);
        variable_set('alt_img_derecha', $edit['alt_img_derecha']);

    }
}

/*
* Hook_view - Devuelve al tpl del core, el html a incrustar
*/
function ardistro_footer_block_view($delta='') {
    $block = array();
    switch($delta) {
        case 'my_block' :
            $block['content'] = _my_custom_module_helper_function();
            break;
    }
    return $block;
}

   
/**
 * @return string
 *   Helper para el html que se usa en el tpl del core
 */
function _my_custom_module_helper_function() {
    // $id = variable_get('my_image_block_image');
    // $oImg = entity_load('file', array($id, array()));
    // $srcImg = file_create_url($oImg[$id]->uri);
    // $altImgIzquierda = variable_get("alt_img_izquierda");

    $img = entity_load_single('file', variable_get('my_image_block_image'));
    $img = !empty($img)? theme('image', 
        array(
            'path' => $img->uri,
            'alt' => $img->alt,
            'title' => $img->title,
            )
        ) : '';

    // $id2 = variable_get('my_image_block_image2');    
    // $oImg2 = entity_load('file', array($id2, array()));
    // $srcImg2 = file_create_url($oImg2[$id2]->uri);
    // $altImgDerecha = variable_get("alt_img_derecha");
    
    $img2 = entity_load_single('file', variable_get('my_image_block_image2'));
    $img2 = !empty($img2)? theme('image', 
        array(
            'path' => $img2->uri,
            'alt' => $img2->alt,
            'title' => $img2->title,
            )
        ): '';
    

    $text = variable_get("texto");

    // $img = "<img src='".$srcImg."' alt='".$altImgIzquierda."' />";
    $text = nl2br($text);
    // $img2 = "<img src='".$srcImg2."' alt='".$altImgDerecha."'  />";
    
    return '<div class="footer-municipio clearfix">'
            .'<div class="col-md-4 logo-municipio">'
            .$img
            .'</div>'
            .'<div class="col-md-4 info-municipio">'
            .$text
            .'</div>'
            .'<div class="col-md-4 telefono_municipio">'
            .$img2
            .'</div>'
            .'</div>'
    ;
}

